spring:
  application:
    name: s-user
  datasource:
    url: jdbc:mysql://localhost:3306/study-skywalking?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: "root"
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 10
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 10
      max-wait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 2000
      # 一个连接在池中最小的空闲时间
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      phy-timeout-millis: 1800000
      phy-max-use-count: 10000
      keep-alive: true
  redis:
    database: 0
    host: localhost
    port: 6379

mybatis:
  typeAliasesPackage: com.wyyl.study.skywalking.common.bean
  mapperLocations: classpath:/mapper/*.xml

dubbo:
  scan:
    base-packages: com.wyyl.study.skywalking.user.service.impl
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 7101
  consumer:
    check: false

aliyun:
  rocket:
    accessKey: AccessKey
    accessSecret: SecretKey
    namesrv: http://127.0.0.1:9876
    groupId: GID_SERVICE_STATISTICS_TEST