apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  ports:
    - protocol: TCP
      port: 8848
      targetPort: 8848

---

apiVersion: v1
kind: Endpoints
metadata:
  name: nacos
subsets:
  - addresses:
      - ip: 192.168.0.101